config/routes.rb
Rails.application.routes.draw do
  get 'orders/show'
  root 'items#index'
  devise_for :users, controllers: {
    registrations: 'users/registrations',
    sessions: 'users/sessions'
  }
  resources :orders, only: [:show]
  resources :users, only: [:show, :edit, :update]
  resources :items, only: [:index, :show]
  resources :carts, only: [:show, :create, :edit, :update, :destroy] do
    delete 'remove_item/:item_id', to: 'carts#remove_item', as: 'remove_item'
    post 'add_item/:item_id', to: 'carts#add_item', as: 'add_item'
    post 'confirm_order', to: 'carts#confirm_order', as: 'confirm_order'
  end

  scope '/checkout' do
    post 'create', to: 'checkout#create', as: 'checkout_create'
    get 'success', to: 'checkout#success', as: 'checkout_success'
    get 'cancel', to: 'checkout#cancel', as: 'checkout_cancel'
  end

  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check
end

app/models/item.rb
class Item < ApplicationRecord
  has_many :cart_items, dependent: :destroy
  has_many :carts, through: :cart_items
  has_many :order_items
  has_many :orders, through: :order_items

  validates :title, presence: true
  validates :description, presence: true
  validates :price, presence: true, numericality: { greater_than_or_equal_to: 0 }
  #validates :image_url, presence: true, format: { with: URI::DEFAULT_PARSER.make_regexp(%w[http https]) }
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  def index
    @items = Item.all
  end

  def show
    @item = Item.find(params[:id])
  end

end

app/helpers/items_helper.rb
module ItemsHelper
end

app/views/items/index.html.erb
<section class="py-5">
    <div class="container px-4 px-lg-5 mt-5">
        <div class="row gx-4 gx-lg-5 row-cols-2 row-cols-md-3 row-cols-xl-4 justify-content-center">
            <% @items.each do |item| %>
                <div class="col mb-5">
                    <div class="card h-100">
                        <!-- Product image-->
                        <img class="card-img-top" src="<%= item.image_url %>" alt="<%= item.title %>" />
                        <!-- Product details-->
                        <div class="card-body p-4">
                            <div class="text-center">
                                <!-- Product name-->
                                <h5 class="fw-bolder"><%= item.title %></h5>
                                <!-- Product price-->
                                <%= number_to_currency(item.price) %>
                            </div>
                        </div>
                        <!-- Product actions-->
                        <div class="card-footer p-4 pt-0 border-top-0 bg-transparent">
                            <div class="text-center">
                                <%= link_to "Voir plus", item_path(item), class: "btn btn-outline-dark mt-auto" %>
                            </div>
                        </div>
                    </div>
                </div>
            <% end %>
        </div>
    </div>
</section>

app/views/items/show.html.erb
<section class="py-5">
    <div class="container px-4 px-lg-5 mt-5">
        <div class="row justify-content-center">
            <div class="col-lg-8">
                <div class="card mb-3">
                    <img class="card-img-top" src="<%= @item.image_url %>" alt="<%= @item.title %>">
                    <div class="card-body">
                        <h2 class="card-title fw-bold"><%= @item.title %></h2>
                        <h3 class="card-subtitle mb-2 text-muted"><%= number_to_currency(@item.price) %></h3>
                        <p class="card-text"><%= @item.description %></p>
                        <div class="text-center">
                        <% if user_signed_in? %>
                        <%= form_with url: cart_add_item_path(current_user.cart || current_user.create_cart, @item), method: :post, local: true do %>
                          <%= submit_tag 'Ajouter au panier', class: 'btn btn-outline-dark' %>
                        <% end %>
                    <% else %>
                        <%= link_to 'Log in to add to cart', new_user_session_path, class: 'btn btn-outline-dark' %>
                    <% end %>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>