config/routes.rb
Rails.application.routes.draw do
  get 'orders/show'
  root 'items#index'
  devise_for :users, controllers: {
    registrations: 'users/registrations',
    sessions: 'users/sessions'
  }
  resources :orders, only: [:show]
  resources :users, only: [:show, :edit, :update]
  resources :items, only: [:index, :show]
  resources :carts, only: [:show, :create, :edit, :update, :destroy] do
    delete 'remove_item/:item_id', to: 'carts#remove_item', as: 'remove_item'
    post 'add_item/:item_id', to: 'carts#add_item', as: 'add_item'
    post 'confirm_order', to: 'carts#confirm_order', as: 'confirm_order'
  end

  scope '/checkout' do
    post 'create', to: 'checkout#create', as: 'checkout_create'
    get 'success', to: 'checkout#success', as: 'checkout_success'
    get 'cancel', to: 'checkout#cancel', as: 'checkout_cancel'
  end

  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/cart.rb
class Cart < ApplicationRecord
  belongs_to :user
  has_many :cart_items, dependent: :destroy
  has_many :items, through: :cart_items

  validates :user, presence: true
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
  belongs_to :cart
  belongs_to :item

  validates :cart, presence: true
  validates :item, presence: true
end

app/models/item.rb
class Item < ApplicationRecord
  has_many :cart_items, dependent: :destroy
  has_many :carts, through: :cart_items
  has_many :order_items
  has_many :orders, through: :order_items

  validates :title, presence: true
  validates :description, presence: true
  validates :price, presence: true, numericality: { greater_than_or_equal_to: 0 }
  #validates :image_url, presence: true, format: { with: URI::DEFAULT_PARSER.make_regexp(%w[http https]) }
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :user
  has_many :order_items, dependent: :destroy
  has_many :items, through: :order_items
end

app/models/order_item.rb
class OrderItem < ApplicationRecord
  belongs_to :order
  belongs_to :item
end

app/models/user.rb
class User < ApplicationRecord
  after_create :create_cart

  has_one :cart, dependent: :destroy
  has_many :orders, dependent: :destroy
  after_create :create_cart
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable



end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_cart, only: [:show, :edit, :update, :destroy, :confirm_order]

  def show
    @cart = current_user.cart
    @cart_items = @cart.cart_items
    @total_price = @cart.items.sum(&:price)

  end

  def edit
    @cart = Cart.find(params[:id])
   end

  def create
    @cart = current_user.build_cart
    if @cart.save
      redirect_to @cart, notice: 'Votre panier a été créé avec succès.'
    else
      render :new
    end
  end

  def update
    @cart = current_user.cart
    if @cart.update(cart_params)
      redirect_to @cart, notice: 'Votre panier a été mis à jour avec succès.'
    else
      render :edit
    end
  end

  def destroy
    @cart = current_user.cart
    @cart.destroy
    redirect_to root_path, notice: 'Votre panier a été supprimé avec succès.'
  end

  def add_item
    @cart = current_user.cart || current_user.create_cart
    item = Item.find(params[:item_id])
    @cart.items << item
    redirect_to @cart, notice: 'L\'article a été ajouté à votre panier.'
  end

  def remove_item
    @cart = current_user.cart
    item = Item.find(params[:item_id])
    @cart.items.delete(item)
    redirect_to @cart, notice: 'L\'article a été retiré de votre panier.'
  end

  def confirm_order
    @cart = current_user.cart
    if @cart.items.any?
      order = current_user.orders.create
      @cart.items.each do |item|
        order.order_items.create(item: item)
      end
      @cart.items.clear
      redirect_to order_path(order), notice: 'Votre commande a été passée avec succès.'
    else
      redirect_to @cart, alert: 'Votre panier est vide.'
    end
  end

  private

  def set_cart
    @cart = current_user.cart || current_user.create_cart
  end

  def cart_params
    params.require(:cart).permit(:user_id)
  end
end

app/controllers/checkout_controller.rb
class CheckoutController < ApplicationController
  def create
    @total = params[:total].to_d
    @order_id = params[:order_id]
    @session = Stripe::Checkout::Session.create(
      payment_method_types: ['card'],
      line_items: [
        {
          price_data: {
            currency: 'eur',
            unit_amount: (@total*100).to_i,
            product_data: {
              name: 'Rails Stripe Checkout',
            },
          },
          quantity: 1
        }
      ],
      metadata: {
        order_id: @order_id
      },
      mode: 'payment',
      success_url: checkout_success_url + '?session_id={CHECKOUT_SESSION_ID}',
      cancel_url: checkout_cancel_url
    )
    redirect_to @session.url, allow_other_host: true
  end

  def success
    @session = Stripe::Checkout::Session.retrieve(params[:session_id])
    @payment_intent = Stripe::PaymentIntent.retrieve(@session.payment_intent)
    @order_id = @session.metadata.order_id
  end

  def cancel
  end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  def index
    @items = Item.all
  end

  def show
    @item = Item.find(params[:id])
  end

end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  before_action :authenticate_user!

  def show
    @order = current_user.orders.find(params[:id])
  end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  before_action :set_user

  def show
    @user = User.find(params[:id])
    @orders = @user.orders
  end

  def edit
    @user = current_user
  end

  private

  def set_user
    @user = current_user
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/checkout_helper.rb
module CheckoutHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_flash.html.erb
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>

    <%= flash[:error] %>

app/views/layouts/_footer.html.erb
        <!-- Footer-->
        <footer class="py-5 bg-dark">
            <div class="container"><p class="m-0 text-center text-white">Copyright &copy; Your Website 2023</p></div>
        </footer>

app/views/layouts/_header.html.erb
       <!-- Header-->
        <header class="bg-dark py-5">
            <div class="container px-4 px-lg-5 my-5">
                <div class="text-center text-white">
                    <h1 class="display-4 fw-bolder">Kitten, les chatons qui te déçoivent !</h1>
                    <p class="lead fw-normal text-white-50 mb-0">C'est notre proooojeeeeet</p>
                </div>
            </div>
        </header>

app/views/layouts/_nav.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <div class="container px-4 px-lg-5">
        <a class="navbar-brand">😼 K I T T E N</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation"><span class="navbar-toggler-icon"></span></button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0 ms-lg-4">
                <li class="nav-item"><a class="nav-link active" aria-current="page" href="<%= root_path %>">Home</a></li>
                <% if user_signed_in? %>
                    <!-- Afficher "Mon profil" et "Déconnexion" si l'utilisateur est connecté -->
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" id="navbarDropdown" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">Mon compte</a>
                        <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                            <li><a class="dropdown-item" href="<%= user_path(current_user) %>">Profil</a></li>
                            <li>
                              <%= form_tag(destroy_user_session_path, method: :delete) do %>
                              <%= button_tag(type: 'submit', class: 'dropdown-item', style: 'background: none; border: none; cursor: pointer;') do %>
                              Se déconnecter
                              <% end %>
                              <% end %>
                        </ul>
                    </li>
                    <% if current_user.cart.present? %>
                      <li class="nav-item"><a class="nav-link" href="<%= cart_path(current_user.cart) %>">Mon panier</a></li>
                    <% end %>
                <% else %>
                    <!-- Afficher "Se connecter / S'inscrire" si l'utilisateur n'est pas connecté -->
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" id="navbarDropdown" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">Sign in/up</a>
                        <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                            <li><a class="dropdown-item" href="<%= new_user_session_path %>">Se connecter</a></li>
                            <li><a class="dropdown-item" href="<%= new_user_registration_path %>">S'inscrire</a></li>
                        </ul>
                    </li>
                <% end %>
            </ul>
        </div>
    </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
    <meta name="description" content="" />
    <meta name="author" content="" />
    <title>😼 Kitten</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= stylesheet_link_tag 'styles', media: 'all', 'data-turbolinks-track': 'reload' %>

    <%= javascript_importmap_tags %>
    <!-- Favicon-->
    <link rel="icon" type="image/x-icon" href="assets/favicon.ico" />
    <!-- Core theme CSS -->
    <link href="styles.css" rel="stylesheet" />
    <!-- Stripe -->
    <script src="https://js.stripe.com/v3/"></script>
</head>

<body>
    <%= render 'layouts/nav' %>
    <%= render 'layouts/header' %>
    <%= render 'layouts/flash'%>
    <%= yield %>
    <%= render 'layouts/footer'%>
    
    <!-- Core theme JS-->
    <script src="scripts.js"></script>
</body>
</html>